由于node的回调异步特性，无法通过try catch来捕捉所有的异常。

这个模块做的就是 try catch 所无法做到的：捕捉异步回调中出现的异常。 